### ISSUE TITLE
addFriend() is not working.

### ISSUE THREAD

**Issue by jinetty** [DarkyEG/discord.js-plus#2]
I tried mention to get ID but also tried your example that is "client.users.cache.get(ID).addFriend().then( () => console.log(etc.) ).catch(console.error); "
![resim](https://user-images.githubusercontent.com/64617882/100335776-69444f00-2fe6-11eb-8c14-9d042d0b8ee0.png)

My Code is
![resim](https://user-images.githubusercontent.com/64617882/100335827-77926b00-2fe6-11eb-892b-f8d56d5bd268.png)

BTW, there is warning about Promise\<User\>
![resim](https://user-images.githubusercontent.com/64617882/100335869-824d0000-2fe6-11eb-8f74-7e65c51f1a0a.png)

Maybe this is the problem's source.

**Comment by jinetty** [comment]
I solved this problem by searching warning on your package and the troubleshoot is simple. You have writed addFreind(), i edited addFriend() . but now, there is new error.

![resim](https://user-images.githubusercontent.com/64617882/100385358-6a4f9d80-3033-11eb-8a0e-3711b426958f.png)

**Comment by darkyeg** [comment]
We apologize for the delay in responding, I forgot about this library, but we will be back with a new version soon
