### ISSUE TITLE
addFriend() is not working

### ISSUE THREAD

**Issue by BlasterStudios** [DarkyEG/discord.js-plus#4]
Whenever I try using the addFriend function it doesnt work and gives me this error: `client.users.cache.get(...).addFriend is not a function`

I even tried copying the example and it gives me the same error
```
const { Client } = require('discord.js-plus')
const client = new Client();
 
client.on('ready', async() => {
 
    client.users.cache.get('ID').addFriend().then( () => {
        console.log('A friend request has been sent')
    }).catch(console.error)
 
})
```

**Comment by darkyeg** [comment]
There is a typo in the function name `addFreind`
We apologize for the delay in responding, I forgot about this library, but we will be back with a new version soon.
